import{countsToCsv,searchProducts,validateQuantity}from"./src/inventory.js";
const $=s=>document.querySelector(s),els={protocol:$("#protocol-label"),status:$("#status-badge"),warning:$("#setup-warning"),start:$("#start-button"),finish:$("#finish-button"),form:$("#count-form"),search:$("#product-search"),results:$("#search-results"),selected:$("#selected-product"),selectedDescription:$("#selected-description"),selectedDetails:$("#selected-details"),quantity:$("#quantity"),submit:$("#submit-count"),badge:$("#count-badge"),summary:$("#list-summary"),empty:$("#empty-list"),list:$("#count-list"),export:$("#export-button"),startDialog:$("#start-dialog"),startCopy:$("#start-dialog-copy"),existing:$("#existing-inventories"),newInventory:$("#new-inventory-button"),settingsDialog:$("#settings-dialog"),settingsForm:$("#settings-form"),apiUrl:$("#api-url"),toast:$("#toast")};
const state={products:[],selectedProduct:null,counts:[],protocol:localStorage.getItem("inventoryProtocol")||"",status:"idle",apiUrl:localStorage.getItem("inventoryApiUrl")||window.INVENTORY_CONFIG?.apiUrl||""};
function toast(message,error=false){els.toast.textContent=message;els.toast.classList.toggle("is-error",error);els.toast.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.hidden=true,3600)}
function busy(button,on,label){button.dataset.label||=button.textContent;button.disabled=on;button.textContent=on?label:button.dataset.label}
async function api(action,payload={}){if(!state.apiUrl)throw Error("Configure a integração com o Google Sheets.");const response=await fetch(state.apiUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});if(!response.ok)throw Error("Não foi possível acessar o Google Sheets.");const result=await response.json();if(!result.ok)throw Error(result.error||"A operação não pôde ser concluída.");return result.data}
function renderStatus(){const open=state.status==="open";els.protocol.textContent=state.protocol||"Nenhum inventário iniciado";els.status.textContent=open?"Aberto":state.status==="closed"?"Finalizado":"Aguardando";els.status.className=`status-badge status-${open?"open":state.status==="closed"?"closed":"idle"}`;els.finish.disabled=!open;els.search.disabled=!open;els.quantity.disabled=!open||!state.selectedProduct;els.submit.disabled=!open||!state.selectedProduct;els.warning.hidden=!!state.apiUrl}
function renderCounts(){els.badge.textContent=state.counts.length;els.summary.textContent=`${state.counts.length} ${state.counts.length===1?"produto":"produtos"}`;els.empty.hidden=state.counts.length>0;els.export.disabled=!state.counts.length;els.list.replaceChildren(...state.counts.map(item=>{const row=document.createElement("article");row.className="count-item";const info=document.createElement("div"),desc=document.createElement("strong"),meta=document.createElement("span"),qty=document.createElement("span");desc.textContent=item.descricao;meta.className="meta";meta.textContent=`ID ${item.idProduto} · EAN ${item.ean||"não informado"}`;qty.className="quantity-pill";qty.textContent=item.quantidade;info.append(desc,meta);row.append(info,qty);return row}))}
function clearSelection(){state.selectedProduct=null;els.search.value="";els.quantity.value="";els.selected.hidden=true;els.results.hidden=true;renderStatus()}
function selectProduct(product){state.selectedProduct=product;els.search.value=product.descricao;els.selectedDescription.textContent=product.descricao;els.selectedDetails.textContent=`ID ${product.idProduto} · EAN ${product.ean||"não informado"}`;els.selected.hidden=true;els.selected.hidden=false;els.results.hidden=true;renderStatus();els.quantity.focus()}
function renderSearch(){const matches=searchProducts(state.products,els.search.value);els.results.replaceChildren(...matches.map(product=>{const li=document.createElement("li");li.className="search-result";li.tabIndex=0;li.role="option";const strong=document.createElement("strong"),span=document.createElement("span");strong.textContent=product.descricao;span.textContent=`ID ${product.idProduto} · EAN ${product.ean||"não informado"}`;li.append(strong,span);li.onclick=()=>selectProduct(product);li.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")selectProduct(product)};return li}));els.results.hidden=!matches.length}
async function refresh(){if(!state.protocol||!state.apiUrl)return;try{const data=await api("getInventory",{protocol:state.protocol});state.status=data.status;state.counts=data.counts;if(data.status!=="open")localStorage.removeItem("inventoryProtocol")}catch(error){state.protocol="";state.status="idle";state.counts=[];localStorage.removeItem("inventoryProtocol");toast(error.message,true)}renderStatus();renderCounts()}
async function activate(mode,protocol=""){busy(els.newInventory,true,"Abrindo...");try{const data=await api("startInventory",{mode,protocol});state.protocol=data.protocol;state.status="open";state.counts=data.counts||[];localStorage.setItem("inventoryProtocol",state.protocol);els.startDialog.close();renderStatus();renderCounts();clearSelection();toast(`Inventário ${state.protocol} aberto.`)}catch(error){toast(error.message,true)}finally{busy(els.newInventory,false)}}
async function openStart(){if(!state.apiUrl){openSettings();return}busy(els.start,true,"Consultando...");try{const data=await api("getStartOptions");els.existing.replaceChildren();els.startCopy.textContent=data.inventories.length?"Reabra um inventário de hoje ou crie um novo.":"Nenhum inventário foi criado hoje. Crie o primeiro para começar.";data.inventories.forEach(inv=>{const button=document.createElement("button");button.type="button";button.className="inventory-option";const strong=document.createElement("strong"),span=document.createElement("span");strong.textContent=inv.protocol;span.textContent=inv.status==="open"?"Aberto":"Finalizado";button.append(strong,span);button.onclick=()=>activate("reopen",inv.protocol);els.existing.append(button)});els.startDialog.showModal()}catch(error){toast(error.message,true)}finally{busy(els.start,false)}}
els.search.oninput=()=>{state.selectedProduct=null;els.selected.hidden=true;renderStatus();renderSearch()};els.search.onkeydown=e=>{if(e.key==="Escape")els.results.hidden=true};document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap"))els.results.hidden=true});
els.form.onsubmit=async e=>{e.preventDefault();const quantity=validateQuantity(els.quantity.value);if(!state.selectedProduct||!quantity)return toast("Selecione um produto e informe uma quantidade inteira maior que zero.",true);busy(els.submit,true,"Enviando...");try{const data=await api("addCount",{protocol:state.protocol,product:state.selectedProduct,quantity});state.counts=data.counts;renderCounts();clearSelection();toast("Contagem registrada.");els.search.focus()}catch(error){toast(error.message,true)}finally{busy(els.submit,false);renderStatus()}};
els.start.onclick=openStart;els.newInventory.onclick=()=>activate("new");els.finish.onclick=async()=>{if(!confirm(`Finalizar o inventário ${state.protocol}?`))return;busy(els.finish,true,"Finalizando...");try{await api("finalizeInventory",{protocol:state.protocol});state.status="closed";localStorage.removeItem("inventoryProtocol");renderStatus();clearSelection();toast("Inventário finalizado.")}catch(error){toast(error.message,true)}finally{busy(els.finish,false);renderStatus()}};
els.export.onclick=()=>{const url=URL.createObjectURL(new Blob([countsToCsv(state.counts)],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`${state.protocol||"inventario"}.csv`;link.click();URL.revokeObjectURL(url)};
document.querySelectorAll(".tab").forEach(tab=>tab.onclick=()=>document.querySelectorAll(".tab").forEach(item=>{const active=item===tab;item.classList.toggle("is-active",active);item.setAttribute("aria-selected",String(active));$(`#${item.dataset.tab}`).hidden=!active}));
function openSettings(){els.apiUrl.value=state.apiUrl;els.settingsDialog.showModal()}$("#settings-button").onclick=openSettings;$("#setup-link").onclick=openSettings;$("[data-close-dialog]").onclick=()=>els.settingsDialog.close();$("#clear-settings").onclick=()=>{state.apiUrl="";localStorage.removeItem("inventoryApiUrl");els.apiUrl.value="";renderStatus()};
els.settingsForm.onsubmit=async e=>{e.preventDefault();const value=els.apiUrl.value.trim();if(!/^https:\/\/script\.google\.com\/.+\/exec(?:\?.*)?$/.test(value))return toast("Informe um endereço publicado do Google Apps Script terminado em /exec.",true);state.apiUrl=value;localStorage.setItem("inventoryApiUrl",value);els.settingsDialog.close();renderStatus();await refresh();toast("Integração salva.")};
async function init(){try{const response=await fetch("./data/products.json",{cache:"no-cache"});if(!response.ok)throw Error();state.products=await response.json()}catch{toast("O cadastro de produtos não pôde ser carregado.",true)}renderStatus();renderCounts();await refresh();if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{})}init();
