const CONTROL_SHEET="_INVENTARIOS",CONTROL_HEADERS=["PROTOCOLO","DATA","STATUS","CRIADO_EM","FINALIZADO_EM"],COUNT_HEADERS=["IDPRODUTO","EAN","DESCRICAOPRODUTO","QUANTIDADE","ULTIMA_CONTAGEM_EM"];
function doGet(){return jsonResponse_({ok:true,data:{service:"INV-SUPRIMENTO",status:"online"}})}
function doPost(e){try{const request=JSON.parse(e.postData.contents||"{}"),handlers={getStartOptions:getStartOptions_,startInventory:startInventory_,getInventory:getInventory_,addCount:addCount_,finalizeInventory:finalizeInventory_};if(!handlers[request.action])throw Error("Ação inválida.");return jsonResponse_({ok:true,data:handlers[request.action](request)})}catch(error){return jsonResponse_({ok:false,error:error.message||"Erro interno."})}}
function setup(){const spreadsheet=SpreadsheetApp.getActiveSpreadsheet();if(!spreadsheet)throw Error("Abra este script a partir da planilha INV-SUPRIMENTO.");PropertiesService.getScriptProperties().setProperty("SPREADSHEET_ID",spreadsheet.getId());ensureControlSheet_();return `Configuração concluída para ${spreadsheet.getName()}.`}
function getStartOptions_(){const today=protocolBase_();return{inventories:readControl_().filter(i=>i.protocol===today||i.protocol.indexOf(`${today}-`)===0).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}}
function startInventory_(request){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=spreadsheet_(),control=ensureControlSheet_();let protocol;if(request.mode==="reopen"){protocol=validateProtocol_(request.protocol);const row=findControlRow_(control,protocol);if(!row)throw Error("Inventário não encontrado.");control.getRange(row,3).setValue("ABERTO");control.getRange(row,5).clearContent()}else if(request.mode==="new"){protocol=nextProtocol_();const sheet=ss.insertSheet(protocol);sheet.getRange(1,1,1,COUNT_HEADERS.length).setValues([COUNT_HEADERS]);formatCountSheet_(sheet);control.appendRow([protocol,new Date(),"ABERTO",new Date(),""])}else throw Error("Escolha reabrir ou criar um novo inventário.");return{protocol,status:"open",counts:readCounts_(ss.getSheetByName(protocol))}}finally{lock.releaseLock()}}
function getInventory_(request){const protocol=validateProtocol_(request.protocol),control=ensureControlSheet_(),row=findControlRow_(control,protocol);if(!row)throw Error("Inventário não encontrado.");const status=String(control.getRange(row,3).getValue()).toUpperCase()==="ABERTO"?"open":"closed";return{protocol,status,counts:readCounts_(spreadsheet_().getSheetByName(protocol))}}
function addCount_(request){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const protocol=validateProtocol_(request.protocol);assertOpen_(protocol);const product=request.product||{},id=cleanText_(product.idProduto,80),ean=cleanText_(product.ean,80),description=cleanText_(product.descricao,500),quantity=Number(request.quantity);if(!id||!description)throw Error("Produto inválido.");if(!Number.isInteger(quantity)||quantity<=0)throw Error("A quantidade deve ser inteira e maior que zero.");const sheet=spreadsheet_().getSheetByName(protocol);if(!sheet)throw Error("A aba do inventário não foi encontrada.");let target=0;if(sheet.getLastRow()>1){const ids=sheet.getRange(2,1,sheet.getLastRow()-1,1).getDisplayValues(),index=ids.findIndex(row=>String(row[0])===id);if(index>=0)target=index+2}if(target){const previous=Number(sheet.getRange(target,4).getValue())||0;sheet.getRange(target,1,1,5).setValues([[id,ean,description,previous+quantity,new Date()]])}else sheet.appendRow([id,ean,description,quantity,new Date()]);return{protocol,counts:readCounts_(sheet)}}finally{lock.releaseLock()}}
function finalizeInventory_(request){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const protocol=validateProtocol_(request.protocol),control=ensureControlSheet_(),row=findControlRow_(control,protocol);if(!row)throw Error("Inventário não encontrado.");control.getRange(row,3).setValue("FINALIZADO");control.getRange(row,5).setValue(new Date());return{protocol,status:"closed"}}finally{lock.releaseLock()}}
function spreadsheet_(){const id=PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID");if(id)return SpreadsheetApp.openById(id);const active=SpreadsheetApp.getActiveSpreadsheet();if(!active)throw Error("Execute a função setup antes de publicar o aplicativo.");return active}
function ensureControlSheet_(){const ss=spreadsheet_();let sheet=ss.getSheetByName(CONTROL_SHEET);if(!sheet){sheet=ss.insertSheet(CONTROL_SHEET);sheet.getRange(1,1,1,CONTROL_HEADERS.length).setValues([CONTROL_HEADERS]);sheet.setFrozenRows(1);sheet.hideSheet()}return sheet}
function readControl_(){const sheet=ensureControlSheet_();if(sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,5).getValues().map(row=>({protocol:String(row[0]),status:String(row[2]).toUpperCase()==="ABERTO"?"open":"closed",createdAt:row[3]instanceof Date?row[3].toISOString():String(row[3]||"")}))}
function readCounts_(sheet){if(!sheet||sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,4).getDisplayValues().map(row=>({idProduto:row[0],ean:row[1],descricao:row[2],quantidade:Number(row[3])||0}))}
function findControlRow_(sheet,protocol){if(sheet.getLastRow()<2)return 0;const index=sheet.getRange(2,1,sheet.getLastRow()-1,1).getDisplayValues().findIndex(row=>row[0]===protocol);return index<0?0:index+2}
function assertOpen_(protocol){const sheet=ensureControlSheet_(),row=findControlRow_(sheet,protocol);if(!row||String(sheet.getRange(row,3).getValue()).toUpperCase()!=="ABERTO")throw Error("O inventário não está aberto.")}
function protocolBase_(){return`INV${Utilities.formatDate(new Date(),spreadsheet_().getSpreadsheetTimeZone(),"ddMMyyyy")}`}
function nextProtocol_(){const base=protocolBase_(),existing=new Set(readControl_().map(i=>i.protocol));if(!existing.has(base))return base;let n=2;while(existing.has(`${base}-${String(n).padStart(2,"0")}`))n++;return`${base}-${String(n).padStart(2,"0")}`}
function validateProtocol_(value){const protocol=String(value||"").trim().toUpperCase();if(!/^INV\d{8}(?:-\d{2,})?$/.test(protocol))throw Error("Protocolo inválido.");return protocol}
function cleanText_(value,max){return String(value??"").replace(/[\r\n\t]/g," ").trim().slice(0,max)}
function formatCountSheet_(sheet){sheet.setFrozenRows(1);sheet.getRange(1,1,1,COUNT_HEADERS.length).setBackground("#0b5d4b").setFontColor("#fff").setFontWeight("bold");[120,140,360,110,180].forEach((width,index)=>sheet.setColumnWidth(index+1,width));sheet.getRange("A:B").setNumberFormat("@");sheet.getRange("D:D").setNumberFormat("0");sheet.getRange("E:E").setNumberFormat("dd/mm/yyyy hh:mm:ss")}
function jsonResponse_(body){return ContentService.createTextOutput(JSON.stringify(body)).setMimeType(ContentService.MimeType.JSON)}
